trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'POPBlog.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'POPBlog.sln'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- script: dotnet pack src/PopBlog.Mvc/PopBlog.Mvc.csproj --configuration $(buildConfiguration) --no-restore --version-suffix "pre.$(Build.BuildId)" --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack'

- script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" --source $(MYGET_SOURCE) --api-key $(MYGET_API_KEY) --skip-duplicate
  displayName: 'Push to MyGet'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
